### ISSUE TITLE
Custom tag names

### ISSUE THREAD

**Issue by dancannon** [ugorji/go#105]
I am looking to convert [dancannon/gorethink](https://github.com/dancannon/gorethink) to using go-codec as the extensions functionality provided by this library should simplify a lot of things in my library. However my project uses different struct tags so I was looking for a way of providing custom tags with this project.

Initially I had the idea of specifying the struct tag in the Handle however this does not work for generated code as the Handle is not know when using code generation. Another idea is just to specify the tag as a package variable however this is not as flexible.  Do you have any other ideas for how this might be achieved?

Slightly related, I was wondering if it was possible to specify custom `Marshaller`/`Unmarshaller` interfaces? For example instead of using `MarshalJSON`/`UnmarshalJSON` I would like to use `MarshalRQL`/`UnmarshalRQL`.

**Comment by ugorji** [comment]
I like the feature request to customize the struct tags. Although it may be only usable by a few folks (e.g. you), it's easy to implement and fits with the vision of the package.

To implement it, I will have to move from using a global variable for the typeInfos, to using one that can be configured on the Handle. If not configure, default to the current behaviour of looking at "codec" and "json" keys (to support codec and migration from the standard library respectively).

I will implement it as follows:

- Define a TypeInfos which can be configured on the Handle
- If not defined, a default one will be used, which looks at codec, json keys
- codecgen will now take a parameter '-st', which will define a comma separated list of keys to inspect

The user will have to work around the possibility of being out-of-sync if using codecgen. However, that is fine, because the user runs codecgen explicitly.

Regarding (M|Unm)arshalRQL, I cannot think of a way to support that, without sacrificing performance. This is because we know the subset of interfaces we care about, and how to handle them, when we inspect the type the first time. At that point, we track whether it implements one of the interfaces, and how many levels of indirection are necessary. Users can only assign extensions based on types.

Unfortunately, I will have to say NO to that request of supporting other interfaces, after careful consideration.

**Comment by dancannon** [comment]
Wow I didnt expect you to work on this so quickly, thank you very much! 

I completely agree with your decision regarding  (M|Unm)arshalRQL, I was not too sure if it was even possible and this library should definitely not sacrifice performance for a feature such as this.
