### ISSUE TITLE
Add support for "string" option for json 

### ISSUE THREAD

**Issue by ascheglov** [ugorji/go#128]
From the docs of "encoding/json":

>  The "string" option signals that a field is stored as JSON inside a JSON-encoded string. It applies only to fields of string, floating point, integer, or boolean types. This extra level of encoding is sometimes used when communicating with JavaScript programs:

>     Int64String int64 `json:",string"`

It would be nice to have such feature to be compatible with the encoding/json.

Also, are there any workarounds which can be used now?

**Comment by ugorji** [comment]
This will not be added. This is a feature that only applies to json, and whose usability is not clear. 

There is no workaround

**Comment by ascheglov** [comment]
This feature might be useful if the other side wants to pass an `int64` number. Many JSON encoders support only `float64` for numbers, so arbitrary int64 numbers can only be passed as strings.

**Comment by mechmind** [comment]
Encoding integer as string is a very important use-case when using JSON for correct interoperability between services implemented in another language. Basically, json numbers often represented as float64 values. This can lead to precision loss:
```
JSON.stringify([12345678901234567890]);
"[12345678901234567000]"
```
Thus, big numbers are often packed into strings.

**Comment by ugorji** [comment]
K. I couldn't find any other encoder/decoder that does something similar (on the encoding side), so there's not a strong case to replicate that ",string" option that go's encoder supports. I've always felt that it was a weak option. Also, remember that codec supports different formats, so there has to be a strong case to add something that only applies to one format to the shared framework.

However, I appreciate and understand the case that encoding large numbers greater than 2^53 will lose precision as your standard JSON (which supports float64). 

What about this to mitigate that real issue:
- Add an option to JsonHandle called LargeIntegerAsString (defaults to false)
- If set, then encode integers > 2^53 (positive or negative) as strings
- During decode, always decode integers from string also

This will elegantly solve the real issue without adding to the struct tags or supporting the ",string" option which I think was a wrong idea to start with. 

Thoughts?

**Comment by ugorji** [comment]
@ascheglov @mechmind please respond soonest. I have some time to work on this today, and if you respond quickly, I should be able to get this in today.

**Comment by mechmind** [comment]
The main issue of proposed solution is inconsistent types after encode - sometimes they will be numbers, sometimes - strings. The peers will not be happy with that.
Cluttering common API with json-specific logic is not good either. Can we mitigate this by tag-specific handlers? E.g. BasicHandle will have a map with handlers and concrete codec populates it with needed handlers on invocation.

**Comment by ugorji** [comment]
I appreciate the concern.

I don't want to get into tag-specific handlers, especially if we can't find a justification for it. That's a re-architecture of the framework, for a niche case that could be handled otherwise.

We really have 3 options within the framework, where an option on JsonHandle will suffice:
- Always encode integers as json number (currently done, default)
- Always encode integers as json strings
- encode integers as json number, except for large integers, which must be encoded as json strings (new option suggesting this)

This means that it cannot be done on a field-by-field level, but on an Encoder level. This should solve the concerns you have, where peers that expect a string will get a string always, but others that expect a number and will want a no-loss-of-precision in the off-chance that a very large integer is specified will get that also.

This may mean that we have an option called say: IntegerAsString byte, which recognizes: 'L' (large integer as string), 'A' (all integers as string), anything else (all integers as json numbers)

**Comment by ugorji** [comment]
@mechmind @ascheglov I'm leaning towards the last stuff I wrote. I will implement it tonight and should submit it tonight or tomorrow. Let me know if you folks have any reservations.

**Comment by ugorji** [comment]
Closing this again. Commit 646ae4a518c1c3be0739df898118d9bccf993858 adds support for IntegerAsString option: L, A, or default.
