### ISSUE TITLE
json.RawMessage encoding perf

### ISSUE THREAD

**Issue by superfell** [ugorji/go#165]
We have a struct that contains a *json.RawMessage field, seeing perf issues with encoding these, looking at the code generated by codecgen, it has this for RawMessage, which seems non-optimal

func (x codecSelfer2443) encjson_RawMessage(v pkg1_json.RawMessage, e *codec1978.Encoder) {
	var h codecSelfer2443
	z, r := codec1978.GenHelperEncoder(e)
	_, _, _ = h, z, r
	r.EncodeArrayStart(len(v))
	for _, yyv1 := range v {
		z.EncSendContainerState(codecSelfer_containerArrayElem2443)
		yym2 := z.EncBinary()
		_ = yym2
		if false {
		} else {
			r.EncodeUint(uint64(yyv1))
		}
	}
	z.EncSendContainerState(codecSelfer_containerArrayEnd2443)
}

**Comment by superfell** [comment]
by comparsion []byte and *[]byte use EncodeStringBytes rather than encoding the array byte at a time.

**Comment by ugorji** [comment]
I will need a reproducer so I can try it out. That way, I can ensure that we are seeing the exact same behaviour, and this is not some form of user error or otherwise.

Please send me a (set of) files that I can run". Include steps to reproduct, and state what you expect to see and what you see.

Thanks.

**Comment by superfell** [comment]
I created a complete standalone example that demonstrates this https://github.com/superfell/codec-enc-issue-165

**Comment by superfell** [comment]
Awesome, thanks!
