### ISSUE TITLE
Msgpack Time Parsing Fails for Strings

### ISSUE THREAD

**Issue by sergiosalvatore** [ugorji/go#228]
Hi,

As of recent versions (I'm not sure exactly when it changed) it's no longer possible to have an extension handle the encoding/decoding of a `time.Time` (at least with the msgpack variant).  In my case, the RPC server returns the time formatted as a string (for instance, "2006-01-02 15:04:05"), so I need to do some custom time parsing.  This was possible back in commit https://github.com/ugorji/go/commit/54210f4 but now is silently disallowed (https://github.com/ugorji/go/blob/master/codec/helper.go#L691).

Would you be opposed to allowing the default time parsing that is now provided to be overridden by calls to `SetExt`?

Thanks!

**Comment by ugorji** [comment]
codec has the concept of built-in types (your standard bool, numbers, string, binary, etc). For all these types, there is a standard way to encode/decode specified by the format itself.

For a while, we treated time.Time as a non built-in type, which was wrong. All the formats specify how to encode/decode them (either in the spec or as a de-facto method). Msgpack also specifies how time should be encoded/decoded in the spec. See https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type

We now streamlined the support so that time.Time is encoded/decoded in the standard way.

There is still full support for custom types. I suggest you make a custom type, and then you can use SetExt to configure how it is encoded/decoded.

i.e. 

```
type CustomTime time.Time
// register it as an extension
// use it in your struct during encoding and decoding, anywhere you had time.Time before, or do a one-line convert as needed.
```

**Comment by sergiosalvatore** [comment]
Thanks for the reply.  I suppose that makes sense.  I would say that there are examples in the documentation that call out creating extensions for msgpack that handle time encoding/decoding, which are now no longer valid.  I'd propose that those be removed.  Also, I think it would make sense for the `SetExt` method to return an error indicating that extensions are not allowed to override the encoding for certain base types (like time) rather than silently return.  This will eliminate some confusion for people developing extensions.  If you agree, I could put a PR together... Thanks!
