### ISSUE TITLE
Encoding from a channel until it is closed

### ISSUE THREAD

**Issue by partomatl** [ugorji/go#233]
I may have missed something but could it be possible to stream encode from a channel until it is closed?

The documentation about iterative streaming support says: 
> Note: When encoding, the length is first retrieved, and only those elements up to the length are encoded from the channel. Any values added to the channel thereafter are not encoded.

What if I do not know how many elements I will receive from the channel?
Is it be possible to do something like that:
```go
var h codec.Handle = new(codec.MsgpackHandle)
var w bytes.Buffer
var bw = bufio.NewWriter(&w)

ch := make(chan object) // channel to encode from
go func() {
    var obj object
    // get objects (e.g. via an iterator) from somewhere, do not know how many though
    iter := somewhere.Get(...)
    for iter.Next(&obj) {
        // maybe do some processing and/or filtering before sending through the channel
        ch <- obj
    }
    close(ch)
}()

var enc = codec.NewEncoder(bw, h)
// encode from channel, and finish when the channel is closed
var err error = enc.Encode(&ch)
```

Again, I may just be missing something here.
Thank you for your work!

**Comment by ugorji** [comment]
I looks the idea, and it actually sounds more correct than the current implementation. Let me think more about it.

**Comment by partomatl** [comment]
Cool, thank you!
The documentation should be updated to remove
> Note: When encoding, the length is first retrieved, and only those elements up to the length are encoded from the channel. Any values added to the channel thereafter are not encoded.


Also, the paragraph just above could lead people to understand that when encoding from a channel, the received values will not be first stored in memory (in a temporary slice), when your implementation actually works that way.
> go-codec will encode a `chan` as an array in the stream. It will also decode an array in the stream into a `chan`. This allows a typical request, where a user wants to decode a very large array **without loading up all the values in memory first in a slice**. This will save memory and CPU time in a BIG WAY.

**Comment by ugorji** [comment]
Yes, I have some changes for the documentation ready to go soon.

I didn't want to have to consume the chan into a slice first, but I couldn't see any other way to accomodate it (as the length of a chan is useless if it is an unbuffered chan or the buffer size is smaller than the number of blocked sends). The old model was handicapped (as you saw). And the cost of storing in a transient slice is low also.

Note that this only affects encoding - and only because most formats want the length prefixed (e.g. messagepack, cbor, binc, etc).  For decoding, we already know the length (as it is prefixed) and we can also just grow the array dynamically if needed, or send into the chan.
