### ISSUE TITLE
Package causing huge binary

### ISSUE THREAD

**Issue by gbbr** [ugorji/go#246]
At Datadog we are using this library in [our tracer](https://github.com/DataDog/dd-trace-go/tree/v1). It is working great! Thanks for writing it!

The problem is that this library, compared to others, is causing a lot of extra (unneeded) Megabytes to be added to the final binary. A simple “hello world” program importing ugorji/go will weigh 12MB!

In my humble opinion, this is not very good. My suggestion is to separate each codec into its own package. Possibly in a “driver” style similar to how database/sql works in the standard library. There are many ways to do this. We only use msgpack and it makes no sense to have everything else in there.

**Comment by ugorji** [comment]
The individual driver struct is but a small fraction of the package. The core if the package is shared by all codecs. Consequently, your suggestion will not do the intended.

Instead, the large size is because of the codecgen usage, or because of the fsst-path support. Fast-path support can be disabled via build tags, where the generated code for far path is elided during the build, and thus is not included in the binary. Pass the build tag: notfastpath
