### ISSUE TITLE
Please provide script(s) to re-build all pre-generated files.

### ISSUE THREAD

**Issue by onlyjob** [ugorji/go#251]
This library should re-generate all pre-built files on build.

That includes `*.tmpl` and `*generated*.go` files.

Currently it is not clear how to generate those files, no build scripts, etc.
I could not find commands to build those files and `go generate` does not help either.

Thanks.

**Comment by ugorji** [comment]
@onlyjob 

Why?

This feels like an uninformed bug report. Why should they be re-generated? What is affecting your use of the library? What functionality do you believe that "go generate" should solve here?

I want to understand your motivation before I shoot an answer that does nothing to solve the concerns you may have, which may be legitimate.

**Comment by onlyjob** [comment]
Shipping pre-built binaries, let alone committing them to repository is usually a bad practice.

Re-building everything generated is good to keep things up to date and for CI purposes as well to ensure that everything is (still) build-able. Also it guarantees that sources are complete/comprehensive and that nothing is missing what's required to build from scratch.
To comply with open source requirements, one have to ship sources for all files in repository...
(shipping source-less files is really bad).

It should be clear _how_ to re-build generated files e.g. they should be accompanied by sources and build scripts. For example user may chose to re-build files to ensure that they are correct e.g. not have been tampered with or directly modified. Pre-built files may have been generated long time ago and forgotten (to update) - you'd be surprised how common such mistakes are. It is not unusual when outdated pre-built files cause practical problems sush as FTBFS in other libraries.

Finally, for some arch-any packages, re-building on various architectures may expose problems otherwise concealed by pre-built components that may even work incorrectly on run-time. This may not be the case for this particular software but anyway.

This is about DFSG compliance, common sense and best practice. :)

**Comment by ugorji** [comment]
This isn't about common sense. And I don't see how this is about DFSG compliance.

You have the source, not a pre-built binary. (This is a lib - which is distributed solely as source, not binary). So - that first line is very inaccurate.

You ensure everything is buildable by running a build. No error - build works. Some artifacts only exist to make it easier to "generate" some helper sources - *.tmpl and co belong to that group. It is not for use by anyone except authors of the library. It is similar to what the go authors do with timezone files, syscall helper files, etc - which are generated as/when the authors deem it necessary, but the generated files are checked into source control and users need not know or care.

The theory for "go generate" is that - the authors run it, especially as the tools needed to generate may not be in the hands of the users. See https://blog.golang.org/generate

```
 Just keep in mind that it is for package authors, not clients, if only for the reason that the program it invokes might not be available on the target machine. Also, if the containing package is intended for import by go get, once the file is generated (and tested!) it must be checked into the source code repository to be available to clients.
``` 

The regeneration is done by the author as needed, so that users just have to grab the source. The quintessential example is "stringer" where the "String" method is generated for a type, and the users never have to know or care.

So - this isn't about DFSG compliance (whatever that is) or common sense (which is kinda insulting to state) or best practice (this is exactly against best practice as defined by the go ecosystem and its use of generated sources). 

Back to my original question. Why?

**Comment by onlyjob** [comment]
I didn't expect that much resistance and to be honest I didn't expect resistance at all...
I don't know how to deal with resistance. Unfortunately Golang community systematically abuses best practice and it is not uncommon to see objections to semantic versioning practices, etc. - a something that other communities more or less accepted as standard practice. Golang is young and I think argument that established or proliferated Golang wrongdoing is a norm just does not stand.

Let's put is this way: how can I re-build all pre-generated files in this repository?

At least you have to document that if not provide scripts that do that. One day you will stop maintaining this repository and your successor will have to figure this out. Now I came across this problem and I would like to see how this could be done.

Finally from free software prospective, generated source (even if human readable) and pre-compiled binary are the same as you have to use compiler to generate both and neither are supposed to be editable by hand. Source-less binaries are non-free and to comply with open source definition, sources of all buildable files should be provided. Building everything from source is a way to guarantee that sources are complete.

I hope that make sense.

**Comment by ugorji** [comment]
Honestly, this bug report started with an over-confident false premise. As much as I might disagree with some decisions of the go team, I have to play in their playground, with the norms that have been accepted by the community. 

Having said that, it is a fair ask to check in the script that generates the files. I can re-introduce that script. Please file a separate issue for that, and I will get to it within the week.

**Comment by onlyjob** [comment]
Thank you.

I wouldn't know what to say in the new issue and I'd rather not make any duplicate ones... Shall we re-title this one instead??

**Comment by onlyjob** [comment]
Thanks. :)
