### ISSUE TITLE
100% cpu usage with net/rpc(*Client) input

### ISSUE THREAD

**Issue by ccampbell** [ugorji/go#271]
Hi there,

I have been using your RPC library in a project I am working on, and for some reason the processes all end up using 100% CPU after running for a while. I have run pprof and the top10 -cum is:

```
      flat  flat%   sum%        cum   cum%
  0.09days  4.01%  4.01%   1.96days 89.77%  net/rpc.(*Client).input
  0.09days  4.06%  8.08%   1.51days 69.41%  phoenix/vendor/github.com/ugorji/go/codec.(*rpcCodec).read
  0.05days  2.51% 10.59%   0.92days 42.01%  runtime.newobject
  0.37days 17.07% 27.66%   0.86days 39.50%  runtime.mallocgc
  0.03days  1.49% 29.15%   0.80days 36.68%  phoenix/vendor/github.com/ugorji/go/codec.(*goRpcCodec).ReadResponseHeader
  0.02days  1.06% 30.21%   0.77days 35.27%  phoenix/vendor/github.com/ugorji/go/codec.(*rpcCodec).ReadResponseBody
  0.09days  3.94% 34.15%   0.49days 22.38%  phoenix/vendor/github.com/ugorji/go/codec.(*rpcCodec).isClosed
  0.01days  0.51% 34.67%   0.31days 14.37%  runtime.systemstack
  0.20days  9.26% 43.93%   0.20days  9.26%  sync.(*RWMutex).RUnlock
  0.20days  9.17% 53.10%   0.20days  9.17%  sync.(*RWMutex).RLock
```

The full PDF of the tree is here:

[profile.pdf](https://github.com/ugorji/go/files/2474368/profile.pdf)

---

I think it is very possible/likely that the issue is on my end, but I have not had a lot of luck debugging, and I am wondering if you have any ideas of places to look or likely culprits. It seems like it could be some sort of leak or race condition that is triggering this bad state. 

One thing I am doing which I could probably change is creating a new tcp connection/client for each RPC call then closing them after (I will likely update this to create one connection per ip and reuse them), but it seems like something is triggering an infinite loop where the RPC client is still looking for a reply after the server has closed the connection or something like that.

I am happy to share the some of the code if that would help.

Thanks in advance.

Oh, and the revision I am using right now is: https://github.com/ugorji/go/tree/b4c50a2b199d93b13dc15e78929cfb23bfdf21ab (last stable release)

**Comment by ugorji** [comment]
Please share a reproducer, so I can see if I can decipher what is happening. I only create the codecs, but still use the net/rpc library, which is typically where the issue may arise from. Does it happen with other codecs?

**Comment by ccampbell** [comment]
Unfortunately, it is going to be fairly involved to write a simple reproduce case (I think). The project is fairly complex (peer to peer networking layer with each peer pinging/monitoring the others to determine latency and broadcasting/relaying encrypted messages to other peers).

I will see what I can do. I will start by trying out the other codecs. Currently I am using `codec.JsonHandle`. Thanks for the quick reply.  I will be in touch next week.

**Comment by ugorji** [comment]
It's hard to solve this one without more information.

I can guess that the constant Lock/Unlock to read/write occurring constantly, whether the Conn is an io.Closer or not, is expensive. I can mitigate this some by using an atomic.Value instead.

However, this is still more in line with optimizing things, than narrowing down exactly where your issue is coming from.

Also, this may be caused by just inefficiencies in the golang runtime or sync primitives or the net/rpc package itself (which our codec just plugs into). I can't make that determination - you will have to do more testing on your usecase to see.

For now, I will make the optimizations to use lock-free methods for rpc, and hope that helps. Please test out the next fix and let me know how it works.

**Comment by ugorji** [comment]
^^ @ccampbell please test the latest fix and let me know how it works. Again, this is kinda a shot in the dark here. If that doesn't help, do some investigation narrowing the issue to the library, ping me again here with a reproducer (just @ugorji on the message) and I can dig in more.

**Comment by ccampbell** [comment]
Thanks! I will try it out and let you know

**Comment by ccampbell** [comment]
I don’t want to jinx it, but the processes have been running for over 3 days now with the new code and using 0% CPU (previously they would be using 100% CPU after just 15-30 mins).

Will keep you updated if anything changes, but thanks so much for the fix!

🎉

**Comment by ugorji** [comment]
^^ @ccampbell 

Nice!

The more we look, the more we see that (RW)Mutex doesn't scale under load. This was the reason why atomic.Value was introduced, and whenever possible, we pay the developer cost to carefully use lock-free programming models (atomic.Value, atomic get/set, etc).

I had eliminated use of RWMutex before, except in the rpc path as I figured most folks were doing low load work with it, and I hadn't heard from anyone about scalability issues there before. Well, you raised the flag, so I figured I would just make the change there and see if that was the culprit.

See golang/go#17973 (with other examples of folks moving from RWMutex due to scalability concerns).
