### ISSUE TITLE
Cannot decode SelfExt types into naked interface with methods

### ISSUE THREAD

**Issue by kostko** [ugorji/go#304]
For some reason when attempting to decode a type that has an extension registered into an interface that has some methods defined, I get the following error:
```
cannot decode non-nil codec value into nil X (Y methods)
```

This seems to be caused by the following code in the decoder:
https://github.com/ugorji/go/blob/0e7b41a4180a29ac92dd9a3621f3fe776a19b6e1/codec/decode.go#L302-L306

If I comment this out, it decodes and works as expected. What is the reason for this error? I don't see why having methods on the interface into which we are decoding should affect said decoding?

**Comment by ugorji** [comment]
I need more context.

Typically, we cannot decode into an interface with methods.

e.g. if we have io.Reader, how do we decode into it? We have to decode into something that implements io.Reader, and we do not know what.

But if we have interface{}, anything can go into it, so we look at the stream and use heuristics to determine the right value (e.g. int64, float64, bool, string, map, slice, etc).

You should only register types as an extension, not interfaces. I will ensure the code handles that explicitly.

**Comment by kostko** [comment]
> You should only register types as an extension, not interfaces. I will ensure the code handles that explicitly.

Yeah I am not registering interfaces.

So a simple example:
```golang
type Foo interface {
    SayHello() string
}

type A struct {
    X string
}

func (a A) SayHello() string {
    return fmt.Sprintf("hello string %s", a.X)
}

type B struct {
    Y int
}

func (b B) SayHello() string {
    return fmt.Sprintf("hello integer %d", b.Y)
}

// Assume A and B are registered as SelfExt extensions.

var decodeIntoMe []Foo
// ...
```

I don't see why decoding into `decodeIntoMe` would not be possible just because `Foo` defines some methods?

**Comment by ugorji** [comment]
Got it.

It works because we are actually decoding into a typed value, and just setting it on the pointer.

It will not work if doing a "naked" decode, i.e. decoding into just an interface where we have to infer the actual type.

Folks were previously having some unrecognizable panics because of this, and so I detected it and put in a formal error.

For the case of extensions, you implicitly define what implementation we provide.

This clearly shows that your use-cases should be supported.

Let me think about how I want to expose this i.e. just remove the restriction, put it behind a flag, etc.
