### ISSUE TITLE
appengine: error during compilation - mapIter and mapRange undefined

### ISSUE THREAD

**Issue by Ramneek-kalra** [ugorji/go#310]
![image](https://user-images.githubusercontent.com/18191513/61614806-3c5d8a80-ac82-11e9-8a28-5f1e84543f3d.png)

**Comment by ugorji** [comment]
I need more context.

What were you doing?

How was it being built?

Can you run this locally?

Does this only happen during "upload"?

What does that mean?

This issue you reported is guaranteed to get zero response, because there are too many unanswered questions. It is similar to me telling you "my car is not working", without any details.

Please provide enough information so I can reproduce and then fix it.

Thanks.

**Comment by ugorji** [comment]
Ah. 

This seems like it has to do with appengine builds. 

Let me look into making sure appengine tag is uniformly handled just like safe tag.
