### ISSUE TITLE
missing go.sum entry needed to verify package

### ISSUE THREAD

**Issue by thinkerou** [ugorji/go#381]
as the follow picture
<img width="984" alt="image" src="https://user-images.githubusercontent.com/4488261/185383920-bcdfa031-b5f4-4f52-9a93-bbbfa6f89227.png">
add go.sum? thanks!

**Comment by ugorji** [comment]
For historical reasons, I have to maintain github.com/ugorji/go and github.com/ugorji/go/codec with a circular dependency (see #299 ).

Consequently, each module has to depend on the "to-be-defined" release tag first, then committed, then that commit tagged, before go.sum can be updated. Due to this, go.sum can only be defined by the users e.g. using a "go mod tidy" call after downloading.

For this reason, we don't include go.sum in the modules. I will add this to the FAQ.
