### ISSUE TITLE
Encode map[int]T with string keys in JSON

### ISSUE THREAD

**Issue by SpiritMachine** [ugorji/go#65]
Such data structures are encoded verbatim, which means the output keys are unquoted, resulting in invalid JSON (standard lib bugs out altogether and just says they're unsupported).

I don't think it's counter-intutive to assume all map keys of the various numeric types will appear in JSON as quoted strings, but others may disagree.

Thoughts on this?

I can have a crack at the PR if the notion is OK with you.

**Comment by ugorji** [comment]
Still thinking about this. My concerns are:

- Symetry issues: If you encode int keys as strings, then we have to be able to decode an int from a string also
- Separation of concerns: Right now, the codec handles do not know whether a map is being encoded. So they don't have a chance to interject and say encode this integer as a string instead.
- Interaction with codecgen: The ripple effect of the change goes beyond just the runtime introspection part. 

As I have thought about it more, I am thinking that this will be hard to design cleanly and implement effectively, while staying true to the design.

I am still thinking about it.

**Comment by ugorji** [comment]
Hi, 

I have thought about this more. I don't think we can do this.

The separation of concerns can be resolved, by having the shared encoding logic handle coercing the non-string reflect.Value to a string reflect.Value and passing that on. This means that the option to treat map keys as a specific type will lie on the encoder (not on the handle). 

However, this is flawed, because limiting the key type to string only makes sense for JsonHandle. If we make this option at the Encoder level, then we should support any specified key type (not just string). If we support any specific key type, then we get into combinatorial coercing which is too much design with little benefit.

Beyond that, the symmetry issue still remains. If we encode a map[int64]T to json, we cannot then decode the json into a map[int64]T without doing coercion on the decoding side, and that logic gets hairy. 

Beyond that, the idea/logic must get propagated/mirrored into the code-generated fast-paths, as they statically handle encoding/decoding of a combination of map types. 

Beyond that, the idea/logic must get propagated/mirrored into the codecgen logic also, which is hairy.

If codec had remained as just a runtime-introspection only library, then the changes would have been contained. Now that we support reflection-free fast-paths for a combination of map (and slice) types and codecgen for any given named type, then any idea/logic in the reflection-based side must be propagated to these hairy code-generated bits. The bar is now much higher for such a change. (The reflection-free paths give incredible performance).

Furthermore, some people (as you alluded to) may fundamentally disagree that this is the right thing to do e.g. encoding/json specifies that maps to be encoded MUST have string types. 

For these reasons, we cannot support this request. I say this with a heavy heart, because I kind of like the request.

**Comment by SpiritMachine** [comment]
Thanks for taking a look and for the clarification.
I think we can get around our particular issue with a custom _selfer_.
