### ISSUE TITLE
usage of codecgen

### ISSUE THREAD

**Issue by gaillard** [ugorji/go#66]
The documentation says to just `codecgen -o outname.go file1.go file2.go`

If file1.go is a file in a main package, I get a main redeclared error. Do the types of which to generate from need to be in a package of their own? Hope not :)

I have also noticed even with code gen that cbor is not even beating the standard libraries json encoding with a simple struct of a few strings and ints.

**Comment by ugorji** [comment]
You cannot run codecgen on a file in the main package. 

This is because codecgen works by creating a temporary main package, which refers to types in an existing package. The temporary main.main() will conflict with the primary main.main(). 

I will update the codecgen code to fail early on this.

Also, please post your benchmark to show stdlib json encoding beating cbor and I will point out the mistake you made.
