### ISSUE TITLE
Headers mention BSD-style license but the license is MIT

### ISSUE THREAD

**Issue by aviau** [ugorji/go#87]
Hello,

go-codec will be available on Debian unstable in the next couple hours.

We noticed that the headers in in your code mention a BSD-style license but the license is actually MIT.

They are different and could cause confusion, maybe you should update your headers.

**Comment by ugorji** [comment]
Snap. 

I don't want to make changes to every file. I am inclined to just change the LICENSE back to the former BSD license there.

Does it make any difference in adoption/usage from your point of view?

**Comment by aviau** [comment]
You can always relicense, but your software was [released under mit](https://tracker.debian.org/pkg/golang-github-ugorji-go-codec).

If you change the license, let me know and I will update the packaging right away.

I am not a direct user of the software, so I can't tell. It is an undirect dependency for InfluxDB, which I am packaging at the moment.

**Comment by ugorji** [comment]
K. I really want to keep the MIT license because it is simpler, and I got tired of reading the differences. 

I'm knee deep in stuff till end of next week. I know it will not take me time to update, but I just gotta fit it into schedule somewhere. I will do it this weekend sometime.

Hope that doesn't hold you back too long. If I forget (which could happen), please just ping this issue over the weekend.

Thanks.

**Comment by aviau** [comment]
> I really want to keep the MIT license 
Perfect :) 

No rush, its not holding me back.
